name: Basic check

on:
  pull_request:
    paths:
      - "apps/signer/**"
    branches: ["main"]

permissions:
  contents: read

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/signer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Build dependencies
        working-directory: .
        run: pnpm --filter passkey-signer --filter passkey-signer-react build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            packages/passkey-signer/dist
            packages/passkey-signer-react/dist

      - name: Run ESLint
        run: pnpm lint

  build:
    name: Build extension
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/signer

    needs:
      - eslint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: packages

      - name: Run build
        working-directory: apps/signer
        run: pnpm build
